[build-system]
requires = [
	"hatchling",
]
build-backend = "hatchling.build"

[project]
name = "namespacepackages"
version = "1.0.0"
description = "Test package for namespace-packages."
requires-python = ">=3.11.5"

dependencies = [
    "ruff"
]